apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config-sol
  namespace: oob
data:
  fluentd-kafka.conf: |
    <source>
      @type tail
      path /logs/*.log
      pos_file /var/log/fluentd-bmc-logs.pos
      tag bmc.logs
      <parse>
          @type regexp
          expression /^(?<host>[^ ]+) - (?<collector_start_epoch>[^ ]+) - (?<collector_counter>[^ ]+) - (?<time>[^ ]+) - (?<message>.*)/
          time_key time
          time_type float
      </parse>
      read_from_head true
    </source>
    <match bmc.logs>
      @type kafka2
      brokers kafka-release-controller-0.kafka-release-controller-headless.kafka.svc.cluster.local:9092,kafka-release-controller-1.kafka-release-controller-headless.kafka.svc.cluster.local:9092,kafka-release-controller-2.kafka-release-controller-headless.kafka.svc.cluster.local:9092
      default_topic bmc_sol
      <format>
        @type json
      </format>

      <inject>
          time_key event_time
          time_type string
          time_format %Y-%m-%dT%H:%M:%S.%NZ
      </inject>

      <buffer>
        flush_interval 5s
      </buffer>
    </match>