FROM jenkins/inbound-agent:3327.v868139a_d00e0-7

USER root
# Install jq and dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        jq \
        ca-certificates \
        curl \
    && rm -rf /var/lib/apt/lists/*

# Install kubectl (latest stable)
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl

USER jenkins