controller:
  image:
    registry: "registry.intel.local:5000"
    repository: "jenkins"
    tag: "1"
  installPlugins: false
  serviceType: LoadBalancer
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  env:
    - name: http_proxy
      value: "http://proxy-dmz.intel.com:912"
    - name: https_proxy
      value: "http://proxy-dmz.intel.com:912"
    - name: no_proxy
      value: "127.0.0.1,localhost,.intel.com,.cluster.local,.intel.local,169.254.25.10/32,10.233.0.0/18,10.49.92.0/23"
  initContainerEnv:
    - name: http_proxy
      value: "http://proxy-dmz.intel.com:912"
    - name: https_proxy
      value: "http://proxy-dmz.intel.com:912"
    - name: no_proxy
      value: "127.0.0.1,localhost,.intel.com,.cluster.local,.intel.local,169.254.25.10/32,10.233.0.0/18,10.49.92.0/23"
    - name: HTTP_PROXY
      value: "http://proxy-dmz.intel.com:912"
    - name: HTTPS_PROXY
      value: "http://proxy-dmz.intel.com:912"
    - name: NO_PROXY
      value: "127.0.0.1,localhost,.intel.com,.cluster.local,.intel.local,169.254.25.10/32,10.233.0.0/18,10.49.92.0/23"
  containerEnv:
    - name: http_proxy
      value: "http://proxy-dmz.intel.com:912"
    - name: https_proxy
      value: "http://proxy-dmz.intel.com:912"
    - name: no_proxy
      value: "127.0.0.1,localhost,.intel.com,.cluster.local,.intel.local,169.254.25.10/32,10.233.0.0/18,10.49.92.0/23"

agent:
  image:
    registry: "registry.intel.local:5000"
    repository: "jenkins/inbound-agent"
    tag: "v1"
  volumes:
    - type: ConfigMap
      configMapName: kubeconfig-cm
      mountPath: /home/jenkins/config
  customJenkinsLabels:
    - ctrls-gnrd
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  yamlTemplate: |-
    apiVersion: v1
    kind: Pod
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
  envVars:
    - name: http_proxy
      value: "http://proxy-dmz.intel.com:912"
    - name: https_proxy
      value: "http://proxy-dmz.intel.com:912"
    - name: no_proxy
      value: "127.0.0.1,localhost,.intel.com,.cluster.local,.intel.local,169.254.25.10/32,10.233.0.0/18,10.49.92.0/23"

persistence:
  enabled: true
  size: "50Gi"
  storageClass: cephfs
