# kubernetes_cluster_setup.yaml
---
- name: Initialize Kubernetes Cluster
  hosts: Master
  become: true
  vars:
    local_kubeadmin_config: "./kubeadm-conf.j2"
    remote_kubeadmin_config: "/{{ ansible_user }}/kubeadm-conf.yaml"
  tasks:
    - name: Copy kubeadmin-config.yaml to remote machine
      template:
        src: "{{ local_kubeadmin_config }}"
        dest: "{{ remote_kubeadmin_config }}"
        owner: "{{ ansible_user }}"
        mode: '0644'

    - name: Ensure kubelet is enabled and started
      systemd:
        name: kubelet
        enabled: yes
        state: started

    - name: Initialize Kubernetes cluster
      command: kubeadm init --config {{ remote_kubeadmin_config }} --ignore-preflight-errors=NumCPU,Mem
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init
      changed_when: kubeadm_init.rc == 0

    - name: Remove old kube config if exists
      file:
        path: "/{{ ansible_user }}/.kube/config"
        state: absent

    - name: Ensure .kube directory exists
      file:
        path: "/{{ ansible_user }}/.kube"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy admin.conf to kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'


    - name: Install Flannel CNI
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      changed_when: false
